name: Add Backlog Status
on:
  issues:
    types: [opened]
jobs:
  Add_New_Issue_To_Project:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/actions-add-new-issue-to-column@v1.1
      with:
        action-token: "${{ secrets.ACCESS_TOKEN }}"
        project-url: "https://github.com/orgs/14A-A-Lyedlik-Devs/projects/3"
        column-name: "Status"
